/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#464748",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#1b1c1d",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#c7c6c7",
        "surface-tint": "#5e5e5f",
        "primary-fixed": "#e3e2e3",
        "on-tertiary-fixed": "#001d35",
        "inverse-primary": "#c7c6c7",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "on-tertiary-fixed-variant": "#25496c",
        "outline-variant": "#c5c6c9",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#3f4753",
        "on-secondary-fixed": "#141c27",
        "secondary-fixed": "#dbe3f2",
        "on-error-container": "#93000a",
        "outline": "#75777a",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "tertiary-fixed": "#d0e4ff",
        "on-secondary": "#ffffff",
        "secondary": "#575f6c",
        "surface-variant": "#e0e3e5",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#a7caf3",
        "on-secondary-container": "#5b6370",
        "on-primary-container": "#848485",
        "on-tertiary-container": "#6487ad",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d8e0ef",
        "tertiary-container": "#001d35",
        "primary-container": "#1b1c1d",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "on-surface-variant": "#45474a",
        "secondary-fixed-dim": "#bfc7d6",
        "primary": "#000000",
        "on-error": "#ffffff",
        "primary-container": "#1b1c1d",
      },
      borderRadius: {
        "DEFAULT": "0.625rem",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "full": "9999px"
      },
      spacing: {
        "md": "1rem",
        "sm": "0.5rem",
        "xs": "0.25rem",
        "lg": "1.5rem",
        "container-max": "1200px",
        "gutter": "1.5rem",
        "base": "4px",
        "xl": "2.5rem"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "label-sm": ["13px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600"}]
      },
      boxShadow: {
        "glass": "0 1px 2px rgba(0,0,0,0.04), 0 4px 16px rgba(0,0,0,0.04)",
        "glass-lg": "0 2px 4px rgba(0,0,0,0.04), 0 8px 32px rgba(0,0,0,0.06)",
        "glass-xl": "0 4px 8px rgba(0,0,0,0.06), 0 16px 48px rgba(0,0,0,0.08)",
        "glow": "0 0 20px rgba(0,0,0,0.08)",
      },
      animation: {
        "float": "float 12s ease-in-out infinite",
        "float-slow": "float 18s ease-in-out infinite",
        "float-fast": "float 8s ease-in-out infinite",
        "gradient-shift": "gradientShift 20s ease infinite alternate",
        "fade-in": "fadeIn 0.5s ease-out forwards",
        "slide-up": "slideUp 0.5s ease-out forwards",
        "scale-in": "scaleIn 0.3s ease-out forwards",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(20px, -30px) scale(1.05)" },
          "66%": { transform: "translate(-15px, 15px) scale(0.95)" },
        },
        gradientShift: {
          "0%": { backgroundPosition: "0% 0%" },
          "50%": { backgroundPosition: "50% 50%" },
          "100%": { backgroundPosition: "100% 100%" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [],
}
